[package]
name = "aardvark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
elsa = "1.7.0"
futures = "0.3.24"

[features]
print_vm_assembly = []
